version: '3.3'

services:
  db:
    image: mariadb:latest
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  php:
    build: ./dockerImages/php
    restart: always
    volumes:
      - ./src:/site

  web:
    image: nginx:latest
    depends_on:
      - db
      - php
    restart: always
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./src:/site
    ports:
      - '80:80'
    links:
      - php
      - db
